# -*- coding: utf-8 -*-
"""Ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pwh_ca65-tTMec04ytdo43aqiD9-17WN
"""

import networkx as nx
import scipy.sparse as sp
import matplotlib.pyplot as plt

G1 = nx.Graph()
G2 = nx.Graph()
G1.add_edges_from([(0, 2), (2, 1), (1, 0)])
G2.add_edges_from([(0, 1), (1, 3), (3, 0), (3, 2)])
matriz1 = nx.adjacency_matrix(G1)
matriz2 = nx.adjacency_matrix(G2)
plt.figure(figsize=(10, 5))
# Gráfico 1
plt.subplot(121)
nx.draw(G1, with_labels=True, node_color='lightblue', node_size=500, edge_color='gray')
plt.title("Gráfico 1")
# Gráfico 2
plt.subplot(122)
nx.draw(G2, with_labels=True, node_color='lightgreen', node_size=500, edge_color='gray')
plt.title("Gráfico 2")
plt.show()
matrizsparce1 = sp.csr_matrix(matriz1)
matrizsparce2 = sp.csr_matrix(matriz2)
print("Matriz dispersa del gráfico 1:")
print(matrizsparce1)
print("\nMatriz dispersa del gráfico 2:")
print(matrizsparce2)